version: '3'
services:
  mqtt-broker:
    image: eclipse-mosquitto:1.6
    expose:
      - 1883
    ports:
      - 1883:1883
      - 8883:8883
      - 9001:9001
    restart: unless-stopped

  core-server:
    build: .
    expose:
      - 9000
    ports:
      - 9000:9000
    depends_on:
      - mqtt-broker
