version: '3'
services:
  mqtt-broker-demo:
    image: eclipse-mosquitto:1.6
    expose:
      - 1884
    ports:
      - 1884:1883
      - 9002:9001
    restart: unless-stopped
  python-demo:
    build: .
    depends_on:
      - mqtt-broker-demo
